"""
RECOVERED: ccxt.static_dependencies.ethereum.abi
"""
# from .abi import ...
# from .base import ...
# from .codec import ...
# from .decoding import ...
# from .encoding import ...
# from .exceptions import ...
# from .grammar import ...
# from .registry import ...
# from .utils import ...
