"""v3

Revision ID: 9f17e744cf77
Revises: 
Create Date: 2024-12-27 20:00:04.999617

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9f17e744cf77"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "ALLOW",
        "NOT_ALLOW",
        "PENDING",
        "SUCCESS",
        "FAILED_AND_CAN_RETRY",
        "FAILED_AND_CAN_NOT_RETRY",
        "CERTIFICATION_DISABLED",
        name="kycstatus",
    ).create(op.get_bind())
    sa.Enum(
        "PROVIDER_SUMSUB",
        "PROVIDER_ONFIDO",
        "PROVIDER_JUMIO",
        "PROVIDER_DEFAULT",
        name="kycprovider",
    ).create(op.get_bind())

    op.create_table(
        "email",
        sa.Column("address", sa.String(length=254), nullable=False),
        sa.Column("imap_address", sa.String(length=254), nullable=True),
        sa.Column("imap_password", sa.String(length=128), nullable=True),
        sa.Column(
            "proxy_error", sa.Boolean(), server_default="FALSE", nullable=False
        ),
        sa.Column(
            "last_login_failed",
            sa.Boolean(),
            server_default="FALSE",
            nullable=False,
        ),
        sa.Column(
            "proxy",
            sa.String(),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("address"),
    )

    op.create_table(
        "bybit_account",

        # ID
        sa.Column("database_id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.Integer(), nullable=True),

        # Group, Name, Note
        sa.Column(
            "group_name",
            sa.String(length=30),
            server_default="no_group",
            nullable=False,
        ),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("note", sa.String(length=1500), nullable=True),

        # Secrets
        sa.Column("email_address", sa.String(length=254), nullable=False),
        sa.Column("password", sa.String(length=128), nullable=True),
        sa.Column("totp_secret", sa.String(length=16), nullable=True),
        sa.Column("payment_password", sa.String(length=30), nullable=True),

        # KYC
        sa.Column("kyc_level", sa.Integer(), nullable=True),
        sa.Column("kyc_provider_telegram_username", sa.String(), nullable=True),

        # Ref
        sa.Column("ref_code", sa.String(), nullable=True),
        sa.Column("inviter_ref_code", sa.String(), nullable=True),

        # Balance
        sa.Column("balance", sa.Float(), server_default="0", nullable=False),
        sa.Column("trading_balance", sa.Float(), server_default="0", nullable=False),
        sa.Column("funding_balance", sa.Float(), server_default="0", nullable=False),
        sa.Column("launchpool_balance", sa.Float(), server_default="0", nullable=False),
        sa.Column("web3_balance", sa.Float(), server_default="0", nullable=False),

        # Proxy
        sa.Column("proxy_error", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.Column(
            "proxy_county_restricted",
            sa.Boolean(),
            server_default="FALSE",
            nullable=False,
        ),
        sa.Column("proxy", sa.String(), nullable=True),
        sa.Column("sumsub_proxy", sa.String(), nullable=True),
        sa.Column("onfido_proxy", sa.String(), nullable=True),

        # API
        sa.Column("api_key", sa.String(), nullable=True),
        sa.Column("api_secret", sa.String(), nullable=True),

        # Login country
        sa.Column("preferred_country_code", sa.String(length=2), nullable=True),
        sa.Column("last_login_country_code", sa.String(length=2), nullable=True),
        sa.Column("last_login_ip", sa.String(), nullable=True),

        # Risk
        sa.Column("can_participate_demo_trading_tournament", sa.Boolean(), nullable=True),
        sa.Column("can_participate_tokensplash", sa.Boolean(), nullable=True),
        sa.Column("can_participate_airdrophunt", sa.Boolean(), nullable=True),
        sa.Column("can_participate_launchpool", sa.Boolean(), nullable=True),
        sa.Column("ido_risk_control", sa.Boolean(), nullable=True),

        # ?_at
        sa.Column("registered_at", sa.DateTime(), nullable=True),
        sa.Column("kyc_completed_at", sa.DateTime(), nullable=True),

        # Statuses
        sa.Column("registered", sa.Boolean(), nullable=True),
        sa.Column("is_autoreg", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=True),
        sa.Column("mobile_verified", sa.Boolean(), nullable=True),
        sa.Column("totp_enabled", sa.Boolean(), nullable=True),
        sa.Column("withdraw_whitelist_enabled", sa.Boolean(), nullable=True),
        sa.Column("web3_wallets_created", sa.Boolean(), nullable=True),
        sa.Column("is_uta", sa.Boolean(), nullable=True),

        # KYC details
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("doc_type", sa.String(), nullable=True),
        sa.Column("doc_number", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),

        sa.Column("need_questionnaire", sa.Boolean(), nullable=True),
        sa.Column(
            "last_provider",
            postgresql.ENUM(
                "PROVIDER_SUMSUB",
                "PROVIDER_ONFIDO",
                "PROVIDER_JUMIO",
                "PROVIDER_DEFAULT",
                name="kycprovider",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "kyc_status",
            postgresql.ENUM(
                "ALLOW",
                "NOT_ALLOW",
                "PENDING",
                "SUCCESS",
                "FAILED_AND_CAN_RETRY",
                "FAILED_AND_CAN_NOT_RETRY",
                "CERTIFICATION_DISABLED",
                name="kycstatus",
                create_type=False,
            ),
            nullable=True,
        ),

        sa.Column(
            "kyc_conflict",
            sa.Boolean(),
            server_default="FALSE",
            nullable=False,
        ),
        sa.Column("kyc_conflict_uid", sa.Integer(), nullable=True),

        # Other
        sa.Column("web3_ido_ton_address", sa.String(), nullable=True),

        sa.Column("adspower_profile_id", sa.String(), nullable=True),
        sa.Column("default_withdraw_address_id", sa.Integer(), nullable=True),
        sa.Column("cookies", sa.JSON(), nullable=True),

        sa.ForeignKeyConstraint(
            ["email_address"],
            ["email.address"],
        ),
        sa.PrimaryKeyConstraint("database_id"),
        sa.UniqueConstraint("totp_secret"),
        sa.UniqueConstraint("uid"),
    )
    op.create_table(
        "airdrophunt",
        sa.Column("code", sa.Integer(), nullable=False),
        sa.Column("uid", sa.Integer(), nullable=False),
        sa.Column("coin_symbol", sa.String(), nullable=True),
        sa.Column("completed", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.Column("spent_usdt", sa.Float(), nullable=False),
        sa.Column("registered_at", sa.DateTime(), nullable=True),
        sa.Column("form_submitted_at", sa.DateTime(), nullable=True),
        sa.Column("answers", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["uid"], ["bybit_account.uid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("code", "uid"),
    )
    op.create_table(
        "deposit_address",
        sa.Column("uid", sa.Integer(), nullable=False),
        sa.Column("coin_symbol", sa.String(), nullable=False),
        sa.Column("chain", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("memo", sa.String(), nullable=False),
        sa.Column("remark", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["uid"], ["bybit_account.uid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("address", "memo", "uid"),
    )
    op.create_table(
        "ido",
        sa.Column("code", sa.BigInteger(), nullable=False),
        sa.Column("uid", sa.Integer(), nullable=False),
        sa.Column("coin_symbol", sa.String(), nullable=True),
        sa.Column("tickets", sa.Integer(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("ticket", sa.String(), nullable=True),
        sa.Column("risk_control", sa.Boolean(), nullable=True),
        sa.Column("airdrop_amount", sa.Float(), nullable=True),
        sa.Column("registered", sa.Boolean(), nullable=True),
        sa.Column("registered_at", sa.DateTime(), nullable=True),
        sa.Column("redeemed", sa.Boolean(), nullable=True),
        sa.Column("approved", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["uid"], ["bybit_account.uid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("code", "uid"),
    )
    op.create_table(
        "tokensplash",
        sa.Column("code", sa.BigInteger(), nullable=False),
        sa.Column("uid", sa.Integer(), nullable=False),
        sa.Column("coin_symbol", sa.String(), nullable=True),
        sa.Column("spent_usdt", sa.Float(), nullable=False),
        sa.Column("volume_usdt", sa.Float(), nullable=False),
        sa.Column("is_new_user", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.Column("registered_at", sa.DateTime(), nullable=True),
        sa.Column("volume_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["uid"], ["bybit_account.uid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("code", "uid"),
    )
    op.create_table(
        "withdraw_address",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.Integer(), nullable=False),
        sa.Column("coin_symbol", sa.String(), nullable=False),
        sa.Column("chain", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("memo", sa.String(), nullable=True),
        sa.Column("remark", sa.String(), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("address_type", sa.Integer(), nullable=False),
        sa.Column("certification_type", sa.Integer(), nullable=False),
        sa.Column("internal_address_type", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["uid"], ["bybit_account.uid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", "uid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("withdraw_address")
    op.drop_table("tokensplash")
    op.drop_table("ido")
    op.drop_table("deposit_address")
    op.drop_table("airdrophunt")
    op.drop_table("bybit_account")
    op.drop_table("email")
    sa.Enum(
        "PROVIDER_SUMSUB",
        "PROVIDER_ONFIDO",
        "PROVIDER_JUMIO",
        "PROVIDER_DEFAULT",
        name="kycprovider",
    ).drop(op.get_bind())
    sa.Enum(
        "ALLOW",
        "NOT_ALLOW",
        "PENDING",
        "SUCCESS",
        "FAILED_AND_CAN_RETRY",
        "FAILED_AND_CAN_NOT_RETRY",
        "CERTIFICATION_DISABLED",
        name="kycstatus",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
