"""withdraw-deposit

Revision ID: 3fa64bff2385
Revises: c9948ecb897a
Create Date: 2024-12-30 00:48:18.190542

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3fa64bff2385"
down_revision: Union[str, None] = "c9948ecb897a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deposit_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.Integer(), nullable=False),
        sa.Column("tx_id", sa.String(), nullable=False),
        sa.Column(
            "internal_deposit_from_member_id", sa.Integer(), nullable=False
        ),
        sa.Column("coin_symbol", sa.String(), nullable=False),
        sa.Column("chain_type", sa.String(), nullable=False),
        sa.Column("chain_name", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("fee", sa.Float(), nullable=False),
        sa.Column("account_type", sa.Integer(), nullable=False),
        sa.Column("deposit_type", sa.Integer(), nullable=False),
        sa.Column("on_chain_deposit_type", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("congested_status", sa.Integer(), nullable=False),
        sa.Column("confirmations", sa.String(), nullable=False),
        sa.Column("transaction_url", sa.String(), nullable=False),
        sa.Column("address_transaction_url", sa.String(), nullable=False),
        sa.Column("safe_confirm_number", sa.Integer(), nullable=False),
        sa.Column("block_confirm_number", sa.Integer(), nullable=False),
        sa.Column("batch_release_limit", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["uid"], ["bybit_account.uid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", "uid"),
    )
    op.create_table(
        "withdraw_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.Integer(), nullable=False),
        sa.Column("tx_id", sa.String(), nullable=False),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("coin_symbol", sa.String(), nullable=False),
        sa.Column("chain_type", sa.String(), nullable=False),
        sa.Column("chain_name", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("fee", sa.Float(), nullable=False),
        sa.Column("account_type", sa.Integer(), nullable=False),
        sa.Column("withdraw_type", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("congested_status", sa.Integer(), nullable=False),
        sa.Column("hot_wallet_status", sa.Integer(), nullable=False),
        sa.Column("transaction_url", sa.String(), nullable=False),
        sa.Column("address_transaction_url", sa.String(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["uid"], ["bybit_account.uid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", "uid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("withdraw_history")
    op.drop_table("deposit_history")
    # ### end Alembic commands ###
