"""ph_str_code

Revision ID: 9cd917163d65
Revises: 22e5815a1920
Create Date: 2025-06-20 18:53:16.845732

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9cd917163d65"
down_revision: Union[str, None] = "22e5815a1920"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("puzzlehunt", schema=None) as batch_op:
        batch_op.alter_column(
            "code",
            existing_type=sa.BIGINT(),
            type_=sa.String(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("puzzlehunt", schema=None) as batch_op:
        batch_op.alter_column(
            "code",
            existing_type=sa.String(),
            type_=sa.BIGINT(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
