"""facial_verification

Revision ID: 2fbdf94a5d4a
Revises: 2976c83b5912
Create Date: 2025-01-18 16:30:42.926805

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2fbdf94a5d4a"
down_revision: Union[str, None] = "2976c83b5912"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bybit_account", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "facial_verification_required",
                sa.Boolean(),
                server_default="FALSE",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bybit_account", schema=None) as batch_op:
        batch_op.drop_column("facial_verification_required")

    # ### end Alembic commands ###
