"""award_use_process

Revision ID: 22e5815a1920
Revises: dee5d4692d6e
Create Date: 2025-06-05 13:09:58.749304

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "22e5815a1920"
down_revision: Union[str, None] = "dee5d4692d6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("award", schema=None) as batch_op:
        batch_op.alter_column("remain_amount_used", new_column_name="use_processed_remain")
        batch_op.alter_column("amount_used", new_column_name="use_processed_value")
        batch_op.alter_column("total_amount_used", new_column_name="use_processed_total")
        batch_op.alter_column("real_total_amount_used", new_column_name="use_processed_real_total")
        batch_op.alter_column("current_amount_used", new_column_name="use_processed_current")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("award", schema=None) as batch_op:
        batch_op.alter_column("use_processed_remain", new_column_name="remain_amount_used")
        batch_op.alter_column("use_processed_value", new_column_name="amount_used")
        batch_op.alter_column("use_processed_total", new_column_name="total_amount_used")
        batch_op.alter_column("use_processed_real_total", new_column_name="real_total_amount_used")
        batch_op.alter_column("use_processed_current", new_column_name="current_amount_used")

    # ### end Alembic commands ###
