"""jsonb_cookies

Revision ID: bb6e74d0db9d
Revises: e033a83a61fd
Create Date: 2025-05-12 16:11:28.220087

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bb6e74d0db9d"
down_revision: Union[str, None] = "e033a83a61fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bybit_account", schema=None) as batch_op:
        batch_op.alter_column(
            "cookies",
            existing_type=postgresql.JSON(astext_type=sa.Text()),
            type_=postgresql.JSONB(astext_type=sa.Text()),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bybit_account", schema=None) as batch_op:
        batch_op.alter_column(
            "cookies",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            type_=postgresql.JSON(astext_type=sa.Text()),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
