"""ACCOUNT_TYPE_MARGIN_STAKE

Revision ID: 245dced0300e
Revises: 571e2c4fdede
Create Date: 2025-03-05 14:17:13.798557

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "245dced0300e"
down_revision: Union[str, None] = "571e2c4fdede"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Переименовываем старый ENUM
    op.execute("ALTER TYPE financeaccounttype RENAME TO financeaccounttype_old")

    # 2. Создаем новый ENUM с добавленным значением
    new_enum = sa.Enum(
        "ACCOUNT_TYPE_FUND",
        "ACCOUNT_TYPE_UNIFIED",
        "ACCOUNT_TYPE_C2C_YBB",
        "ACCOUNT_TYPE_CONTRACT",
        "ACCOUNT_TYPE_LAUNCHPOOL",
        "ACCOUNT_TYPE_COPY_PRO",
        "ACCOUNT_TYPE_COPY_TRADE",
        "ACCOUNT_TYPE_COPY_TRADE_ALL",
        "ACCOUNT_TYPE_INVESTMENT",
        "ACCOUNT_TYPE_PLEDGE_LOANS",
        "ACCOUNT_TYPE_FIXED_RATE_LOAN",
        "ACCOUNT_TYPE_PRE_MARKET_TRADING",
        "ACCOUNT_TYPE_BOT",
        "ACCOUNT_TYPE_MT4",
        "ACCOUNT_TYPE_MT5",
        "ACCOUNT_TYPE_OPTION",
        "ACCOUNT_TYPE_SPOT",
        "ACCOUNT_TYPE_MARGIN_STAKE",  # Новое значение
        name="financeaccounttype",
    )
    new_enum.create(op.get_bind())

    # 3. Обновляем столбец type в таблице finance_account
    op.execute(
        """
        ALTER TABLE finance_account
        ALTER COLUMN type TYPE financeaccounttype
        USING type::text::financeaccounttype
        """
    )

    # 4. Удаляем старый ENUM
    op.execute("DROP TYPE financeaccounttype_old")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Переименовываем текущий ENUM
    op.execute("ALTER TYPE financeaccounttype RENAME TO financeaccounttype_new")

    # 2. Создаем старый ENUM без нового значения
    old_enum = sa.Enum(
        "ACCOUNT_TYPE_FUND",
        "ACCOUNT_TYPE_UNIFIED",
        "ACCOUNT_TYPE_C2C_YBB",
        "ACCOUNT_TYPE_CONTRACT",
        "ACCOUNT_TYPE_LAUNCHPOOL",
        "ACCOUNT_TYPE_COPY_PRO",
        "ACCOUNT_TYPE_COPY_TRADE",
        "ACCOUNT_TYPE_COPY_TRADE_ALL",
        "ACCOUNT_TYPE_INVESTMENT",
        "ACCOUNT_TYPE_PLEDGE_LOANS",
        "ACCOUNT_TYPE_FIXED_RATE_LOAN",
        "ACCOUNT_TYPE_PRE_MARKET_TRADING",
        "ACCOUNT_TYPE_BOT",
        "ACCOUNT_TYPE_MT4",
        "ACCOUNT_TYPE_MT5",
        "ACCOUNT_TYPE_OPTION",
        "ACCOUNT_TYPE_SPOT",
        name="financeaccounttype",
    )
    old_enum.create(op.get_bind())

    # 3. Обновляем столбец type в таблице finance_account
    op.execute(
        """
        ALTER TABLE finance_account
        ALTER COLUMN type TYPE financeaccounttype
        USING type::text::financeaccounttype
        """
    )

    # 4. Удаляем новый ENUM
    op.execute("DROP TYPE financeaccounttype_new")

    # ### end Alembic commands ###