"""proxy_payment_required

Revision ID: 90a4dcea2216
Revises: 4b2139a26b1e
Create Date: 2025-03-28 20:29:30.054542

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "90a4dcea2216"
down_revision: Union[str, None] = "4b2139a26b1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bybit_account", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "proxy_payment_required",
                sa.Boolean(),
                server_default="FALSE",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bybit_account", schema=None) as batch_op:
        batch_op.drop_column("proxy_payment_required")

    # ### end Alembic commands ###
