"""nullable_balances

Revision ID: 3725561d122d
Revises: 4840d1739004
Create Date: 2025-03-18 01:50:07.474384

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3725561d122d"
down_revision: Union[str, None] = "4840d1739004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bybit_account", schema=None) as batch_op:
        batch_op.alter_column(
            "balance_usd",
            existing_type=sa.DOUBLE_PRECISION(precision=53),
            nullable=True,
            existing_server_default=sa.text("'0'::double precision"),
        )

    with op.batch_alter_table("web3_wallet", schema=None) as batch_op:
        batch_op.alter_column(
            "balance_usd",
            existing_type=sa.DOUBLE_PRECISION(precision=53),
            nullable=True,
            existing_server_default=sa.text("'0'::double precision"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("web3_wallet", schema=None) as batch_op:
        batch_op.alter_column(
            "balance_usd",
            existing_type=sa.DOUBLE_PRECISION(precision=53),
            nullable=False,
            existing_server_default=sa.text("'0'::double precision"),
        )

    with op.batch_alter_table("bybit_account", schema=None) as batch_op:
        batch_op.alter_column(
            "balance_usd",
            existing_type=sa.DOUBLE_PRECISION(precision=53),
            nullable=False,
            existing_server_default=sa.text("'0'::double precision"),
        )

    # ### end Alembic commands ###
