"""aai_proxy

Revision ID: 5a93aa0aff0a
Revises: b2e8a44aaad8
Create Date: 2025-05-08 00:06:25.427184

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a93aa0aff0a"
down_revision: Union[str, None] = "b2e8a44aaad8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bybit_account", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "aai_proxy",
                sa.String(),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bybit_account", schema=None) as batch_op:
        batch_op.drop_column("aai_proxy")

    # ### end Alembic commands ###
