"""remove balance fields

Revision ID: d6739d3ab96d
Revises: 8eca72c96c47
Create Date: 2025-02-03 22:45:28.873476

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d6739d3ab96d"
down_revision: Union[str, None] = "8eca72c96c47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bybit_account", schema=None) as batch_op:
        batch_op.drop_column("launchpool_balance")
        batch_op.drop_column("trading_balance")
        batch_op.drop_column("funding_balance")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bybit_account", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "funding_balance",
                sa.DOUBLE_PRECISION(precision=53),
                server_default=sa.text("'0'::double precision"),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "trading_balance",
                sa.DOUBLE_PRECISION(precision=53),
                server_default=sa.text("'0'::double precision"),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "launchpool_balance",
                sa.DOUBLE_PRECISION(precision=53),
                server_default=sa.text("'0'::double precision"),
                autoincrement=False,
                nullable=False,
            )
        )

    # ### end Alembic commands ###
