"""award2

Revision ID: e033a83a61fd
Revises: 556d201c3e5b
Create Date: 2025-05-11 00:26:29.868966

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e033a83a61fd"
down_revision: Union[str, None] = "556d201c3e5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("award", schema=None) as batch_op:
        batch_op.alter_column(
            "amount",
            existing_type=sa.DOUBLE_PRECISION(precision=53),
            type_=sa.String(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("award", schema=None) as batch_op:
        batch_op.alter_column(
            "amount",
            existing_type=sa.String(),
            type_=sa.DOUBLE_PRECISION(precision=53),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
