"""add profit column to account

Revision ID: b239907a4191
Revises: 306785fb131a
Create Date: 2025-08-30 10:24:24.832410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b239907a4191'
down_revision: Union[str, None] = '306785fb131a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bybit_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profit', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bybit_account', schema=None) as batch_op:
        batch_op.drop_column('profit')

    # ### end Alembic commands ###
