"""finance_account

Revision ID: 8eca72c96c47
Revises: 2fbdf94a5d4a
Create Date: 2025-02-02 14:44:54.911581

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8eca72c96c47"
down_revision: Union[str, None] = "2fbdf94a5d4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "ACCOUNT_TYPE_FUND",
        "ACCOUNT_TYPE_UNIFIED",
        "ACCOUNT_TYPE_C2C_YBB",
        "ACCOUNT_TYPE_CONTRACT",
        "ACCOUNT_TYPE_LAUNCHPOOL",
        "ACCOUNT_TYPE_COPY_PRO",
        "ACCOUNT_TYPE_COPY_TRADE",
        "ACCOUNT_TYPE_COPY_TRADE_ALL",
        "ACCOUNT_TYPE_INVESTMENT",
        "ACCOUNT_TYPE_PLEDGE_LOANS",
        "ACCOUNT_TYPE_FIXED_RATE_LOAN",
        "ACCOUNT_TYPE_PRE_MARKET_TRADING",
        "ACCOUNT_TYPE_BOT",
        "ACCOUNT_TYPE_MT4",
        "ACCOUNT_TYPE_MT5",
        "ACCOUNT_TYPE_OPTION",
        "ACCOUNT_TYPE_SPOT",
        name="financeaccounttype",
    ).create(op.get_bind())
    op.create_table(
        "finance_account",
        sa.Column("uid", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "ACCOUNT_TYPE_FUND",
                "ACCOUNT_TYPE_UNIFIED",
                "ACCOUNT_TYPE_C2C_YBB",
                "ACCOUNT_TYPE_CONTRACT",
                "ACCOUNT_TYPE_LAUNCHPOOL",
                "ACCOUNT_TYPE_COPY_PRO",
                "ACCOUNT_TYPE_COPY_TRADE",
                "ACCOUNT_TYPE_COPY_TRADE_ALL",
                "ACCOUNT_TYPE_INVESTMENT",
                "ACCOUNT_TYPE_PLEDGE_LOANS",
                "ACCOUNT_TYPE_FIXED_RATE_LOAN",
                "ACCOUNT_TYPE_PRE_MARKET_TRADING",
                "ACCOUNT_TYPE_BOT",
                "ACCOUNT_TYPE_MT4",
                "ACCOUNT_TYPE_MT5",
                "ACCOUNT_TYPE_OPTION",
                "ACCOUNT_TYPE_SPOT",
                name="financeaccounttype",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("balance", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["uid"], ["bybit_account.uid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("uid", "type"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("finance_account")
    sa.Enum(
        "ACCOUNT_TYPE_FUND",
        "ACCOUNT_TYPE_UNIFIED",
        "ACCOUNT_TYPE_C2C_YBB",
        "ACCOUNT_TYPE_CONTRACT",
        "ACCOUNT_TYPE_LAUNCHPOOL",
        "ACCOUNT_TYPE_COPY_PRO",
        "ACCOUNT_TYPE_COPY_TRADE",
        "ACCOUNT_TYPE_COPY_TRADE_ALL",
        "ACCOUNT_TYPE_INVESTMENT",
        "ACCOUNT_TYPE_PLEDGE_LOANS",
        "ACCOUNT_TYPE_FIXED_RATE_LOAN",
        "ACCOUNT_TYPE_PRE_MARKET_TRADING",
        "ACCOUNT_TYPE_BOT",
        "ACCOUNT_TYPE_MT4",
        "ACCOUNT_TYPE_MT5",
        "ACCOUNT_TYPE_OPTION",
        "ACCOUNT_TYPE_SPOT",
        name="financeaccounttype",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
