"""web3_tables

Revision ID: 4840d1739004
Revises: 4a377279e399
Create Date: 2025-03-17 19:20:25.243841

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4840d1739004"
down_revision: Union[str, None] = "4a377279e399"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "web3_wallet",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("uid", sa.Integer(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "CLOUD",
                "PRIVATE_KEY",
                "MNEMONIC_PHRASE",
                name="numberwallettype",
            ),
            nullable=False,
        ),
        sa.Column(
            "balance_usd", sa.Float(), server_default="0", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["uid"],
            ["bybit_account.uid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "web3_chain",
        sa.Column("wallet_id", sa.String(), nullable=False),
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column(
            "chain_type",
            sa.Enum(
                "ALL",
                "EVM",
                "SUI",
                "SOLANA",
                "BTC",
                "STX",
                "APT",
                "TON",
                "TRON",
                name="web3chaintype",
            ),
            nullable=False,
        ),
        sa.Column("chain_code", sa.String(), nullable=True),
        sa.Column(
            "balance_usd", sa.Float(), server_default="0", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["web3_wallet.id"],
        ),
        sa.PrimaryKeyConstraint("wallet_id", "chain_id"),
    )
    op.create_table(
        "web3_token",
        sa.Column("wallet_id", sa.String(), nullable=False),
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.Column("contract_address", sa.String(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("balance", sa.Float(), nullable=False),
        sa.Column("balance_usd", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["web3_wallet.id"],
        ),
        sa.PrimaryKeyConstraint("wallet_id", "chain_id", "contract_address"),
    )
    with op.batch_alter_table("bybit_account", schema=None) as batch_op:
        batch_op.alter_column("web3_wallets_created", new_column_name="web3_cloud_wallets_created")
        batch_op.alter_column("mnemonic_phrase", new_column_name="web3_mnemonic_phrase")
        batch_op.alter_column("balance", new_column_name="balance_usd")
        batch_op.add_column(
            sa.Column("twitter_auth_token", sa.String(), nullable=True)
        )
        batch_op.create_unique_constraint("unique_web3_mnemonic_phrase", ["web3_mnemonic_phrase"])
        batch_op.drop_column("web3_balance")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("web3_token")
    op.drop_table("web3_chain")
    op.drop_table("web3_wallet")

    with op.batch_alter_table("bybit_account", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "web3_balance",
                sa.DOUBLE_PRECISION(precision=53),
                server_default=sa.text("'0'::double precision"),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_constraint("unique_web3_mnemonic_phrase", type_="unique")
        batch_op.drop_column("twitter_auth_token")
        batch_op.alter_column("web3_cloud_wallets_created", new_column_name="web3_wallets_created")
        batch_op.alter_column("web3_mnemonic_phrase", new_column_name="mnemonic_phrase")
        batch_op.alter_column("balance_usd", new_column_name="balance")
        op.execute("""DROP TYPE web3chaintype""")
        op.execute("""DROP TYPE numberwallettype""")
    # ### end Alembic commands ###
