"""ph_mark

Revision ID: 543fad3c354b
Revises: 90a4dcea2216
Create Date: 2025-04-21 14:38:49.807469

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "543fad3c354b"
down_revision: Union[str, None] = "90a4dcea2216"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bybit_account", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "can_participate_puzzlehunt", sa.Boolean(), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bybit_account", schema=None) as batch_op:
        batch_op.drop_column("can_participate_puzzlehunt")

    # ### end Alembic commands ###
