"""device

Revision ID: b2e8a44aaad8
Revises: 0a46d0f83994
Create Date: 2025-05-05 19:51:04.591204

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2e8a44aaad8"
down_revision: Union[str, None] = "0a46d0f83994"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bybit_account", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("chrome_major_version", sa.Integer(), nullable=True)
        )
        batch_op.add_column(sa.Column("os", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("screen_width", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("screen_height", sa.Integer(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bybit_account", schema=None) as batch_op:
        batch_op.drop_column("screen_height")
        batch_op.drop_column("screen_width")
        batch_op.drop_column("os")
        batch_op.drop_column("chrome_major_version")

    # ### end Alembic commands ###
