"""mnemonic_phrase

Revision ID: 4a377279e399
Revises: d305953c4010
Create Date: 2025-03-12 21:10:33.026086

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a377279e399"
down_revision: Union[str, None] = "d305953c4010"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bybit_account", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("mnemonic_phrase", sa.String(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bybit_account", schema=None) as batch_op:
        batch_op.drop_column("mnemonic_phrase")

    # ### end Alembic commands ###
