"""last_tencent_request_time

Revision ID: 0a46d0f83994
Revises: da83cafe8bb6
Create Date: 2025-04-28 14:39:21.541964

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0a46d0f83994"
down_revision: Union[str, None] = "da83cafe8bb6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bybit_account", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "last_tencent_request_time", sa.DateTime(), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bybit_account", schema=None) as batch_op:
        batch_op.drop_column("last_tencent_request_time")

    # ### end Alembic commands ###
