"""is_rewarded in tokensplash

Revision ID: 306785fb131a
Revises: 9cd917163d65
Create Date: 2025-08-13 22:30:09.176709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '306785fb131a'
down_revision: Union[str, None] = '9cd917163d65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokensplash', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rewarded', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokensplash', schema=None) as batch_op:
        batch_op.drop_column('rewarded')

    # ### end Alembic commands ###
