"""reported_bad

Revision ID: 2976c83b5912
Revises: 3fa64bff2385
Create Date: 2025-01-05 15:37:24.269845

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2976c83b5912"
down_revision: Union[str, None] = "3fa64bff2385"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bybit_account", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "reported_bad",
                sa.Boolean(),
                server_default="FALSE",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bybit_account", schema=None) as batch_op:
        batch_op.drop_column("reported_bad")

    # ### end Alembic commands ###
