"""ph

Revision ID: da83cafe8bb6
Revises: 543fad3c354b
Create Date: 2025-04-27 17:03:14.662611

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "da83cafe8bb6"
down_revision: Union[str, None] = "543fad3c354b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "puzzlehunt",
        sa.Column("code", sa.BigInteger(), nullable=False),
        sa.Column("uid", sa.Integer(), nullable=False),
        sa.Column("coin_symbol", sa.String(), nullable=True),
        sa.Column(
            "registered", sa.Boolean(), server_default="FALSE", nullable=False
        ),
        sa.Column("registered_at", sa.DateTime(), nullable=True),
        sa.Column(
            "social_tasks_completed",
            sa.Boolean(),
            server_default="FALSE",
            nullable=False,
        ),
        sa.Column("checkin_count", sa.Integer(), nullable=False),
        sa.Column("piece_count", sa.Integer(), nullable=False),
        sa.Column("reward_amount", sa.Float(), nullable=False),
        sa.Column("volume_usdt", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["uid"], ["bybit_account.uid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("code", "uid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("puzzlehunt")
    # ### end Alembic commands ###
