"""PROVIDER_AAI

Revision ID: d305953c4010
Revises: 245dced0300e
Create Date: 2025-03-05 15:58:36.438371

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d305953c4010"
down_revision: Union[str, None] = "245dced0300e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Переименовываем старый ENUM
    op.execute("ALTER TYPE kycprovider RENAME TO kycprovider_old")

    # 2. Создаем новый ENUM с добавленным значением
    new_enum = sa.Enum(
        "PROVIDER_SUMSUB",
        "PROVIDER_ONFIDO",
        "PROVIDER_JUMIO",
        "PROVIDER_AAI",
        "PROVIDER_DEFAULT",
        name="kycprovider",
    )
    new_enum.create(op.get_bind())

    # 3. Обновляем столбец type в таблице bybit_account
    op.execute(
        """
        ALTER TABLE bybit_account
        ALTER COLUMN last_provider TYPE kycprovider
        USING last_provider::text::kycprovider
        """
    )

    # 4. Удаляем старый ENUM
    op.execute("DROP TYPE kycprovider_old")

    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade() -> None:
    # 1. Переименовываем текущий ENUM
    op.execute("ALTER TYPE kycprovider RENAME TO kycprovider_new")

    # 2. Создаем старый ENUM без нового значения
    old_enum = sa.Enum(
        "PROVIDER_SUMSUB",
        "PROVIDER_ONFIDO",
        "PROVIDER_JUMIO",
        "PROVIDER_DEFAULT",
        name="kycprovider",
    )
    old_enum.create(op.get_bind())

    # 3. Обновляем столбец type в таблице bybit_account
    op.execute(
        """
        ALTER TABLE bybit_account
        ALTER COLUMN last_provider TYPE kycprovider
        USING last_provider::text::kycprovider
        """
    )

    # 4. Удаляем новый ENUM
    op.execute("DROP TYPE kycprovider_new")
