"""api_key table

Revision ID: 1c68db5b4dc0
Revises: 4e591d5fac96
Create Date: 2026-02-27 14:44:50.913730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c68db5b4dc0'
down_revision: Union[str, None] = '4e591d5fac96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('bybit_id', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.Column('ipv4_addresses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('read_only', sa.Boolean(), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['bybit_account.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bybit_id')
    )

    # 2) data migration (copy non-empty keys)
    op.execute(sa.text("""
        INSERT INTO api_key
            (uid, bybit_id, note, key, secret, ipv4_addresses, read_only, permissions, created_at)
        SELECT
            ba.uid,
            'migrated-' || ba.uid::text       AS bybit_id,
            'migrated'                        AS note,
            ba.api_key                        AS key,
            ba.api_secret                     AS secret,
            '[]'::jsonb                       AS ipv4_addresses,
            false                             AS read_only,
            '{}'::jsonb                       AS permissions,
            now()                             AS created_at
        FROM bybit_account ba
        WHERE
            ba.uid IS NOT NULL
            AND ba.api_key IS NOT NULL AND btrim(ba.api_key) <> ''
            AND ba.api_secret IS NOT NULL AND btrim(ba.api_secret) <> '';
    """))

    op.drop_column("bybit_account", "api_key")
    op.drop_column("bybit_account", "api_secret")

    # ### end Alembic commands ###


def downgrade() -> None:
    with op.batch_alter_table('bybit_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('api_secret', sa.String(), nullable=True))
    op.drop_table('api_key')
    # ### end Alembic commands ###
