"""email fields for outlook

Revision ID: 4e591d5fac96
Revises: 8da7886b84c9
Create Date: 2026-02-04 18:06:51.481763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e591d5fac96'
down_revision: Union[str, None] = '8da7886b84c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('refresh_token', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('client_id')
    # ### end Alembic commands ###
