"""
iCloud Hide My Email generator — creates disposable email aliases.

Based on: https://github.com/rtunazzz/hidemyemail-generator
Requires: iCloud+ subscription, browser cookies from icloud.com

Each alias forwards to your main iCloud email. Bybit sees a unique
@privaterelay.appleid.com address per account.

Limits: ~5 emails per 45 min, ~750 total per iCloud account.
"""

import asyncio
import json
import logging
import os
import ssl
from pathlib import Path
from typing import Any, Dict, List, Optional

import aiohttp

try:
    import certifi
    SSL_CONTEXT = ssl.create_default_context(cafile=certifi.where())
except ImportError:
    SSL_CONTEXT = ssl.create_default_context()

logger = logging.getLogger("bybit_manager.icloud_hme")

# iCloud HideMyEmail API endpoints
HME_BASE_V1 = "https://p68-maildomainws.icloud.com/v1/hme"
HME_BASE_V2 = "https://p68-maildomainws.icloud.com/v2/hme"

DEFAULT_PARAMS = {
    "clientBuildNumber": "2536Project32",
    "clientMasteringNumber": "2536B20",
    "clientId": "",
    "dsid": "",
}

DEFAULT_HEADERS = {
    "Connection": "keep-alive",
    "Content-Type": "text/plain",
    "Accept": "*/*",
    "Origin": "https://www.icloud.com",
    "Referer": "https://www.icloud.com/",
    "Sec-Fetch-Site": "same-site",
    "Sec-Fetch-Mode": "cors",
    "Sec-Fetch-Dest": "empty",
    "Accept-Language": "en-US,en;q=0.9",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"Windows"',
}

# Rate limiting
BATCH_SIZE = 5
BATCH_COOLDOWN = 2700  # 45 minutes in seconds


class HideMyEmailClient:
    """Async client for Apple's Hide My Email service.

    Usage:
        async with HideMyEmailClient(cookies="...") as hme:
            email = await hme.generate_one(label="bybit-acc-1")
            print(email)  # something@privaterelay.appleid.com
    """

    def __init__(
        self,
        cookies: str = "",
        cookie_file: Optional[str] = None,
        label: str = "bybit-manager",
    ):
        self.label = label
        self._cookies = ""
        self._session: Optional[aiohttp.ClientSession] = None

        if cookies:
            self._cookies = cookies.strip()
        elif cookie_file and os.path.exists(cookie_file):
            with open(cookie_file, "r") as f:
                lines = [l.strip() for l in f if l.strip() and not l.startswith("//")]
                self._cookies = lines[0] if lines else ""
        else:
            logger.warning("No iCloud cookies provided — HME generation will fail")

    async def __aenter__(self):
        await self._ensure_session()
        return self

    async def __aexit__(self, *args):
        await self.close()

    async def _ensure_session(self) -> aiohttp.ClientSession:
        if self._session is None or self._session.closed:
            connector = aiohttp.TCPConnector(ssl=SSL_CONTEXT)
            headers = {
                **DEFAULT_HEADERS,
                "Cookie": self._cookies,
                "User-Agent": (
                    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                    "AppleWebKit/537.36 (KHTML, like Gecko) "
                    "Chrome/135.0.0.0 Safari/537.36"
                ),
                "sec-ch-ua": '"Chromium";v="135", "Google Chrome";v="135", "Not-A.Brand";v="99"',
            }
            self._session = aiohttp.ClientSession(
                headers=headers,
                timeout=aiohttp.ClientTimeout(total=15),
                connector=connector,
            )
        return self._session

    async def close(self):
        if self._session and not self._session.closed:
            await self._session.close()
            self._session = None

    async def generate_email(self) -> Dict[str, Any]:
        """Step 1: Generate a new HME address (not yet active)."""
        session = await self._ensure_session()
        try:
            async with session.post(
                f"{HME_BASE_V1}/generate",
                params=DEFAULT_PARAMS,
                json={"langCode": "en-us"},
            ) as resp:
                return await resp.json()
        except asyncio.TimeoutError:
            return {"error": 1, "reason": "Request timed out"}
        except Exception as e:
            return {"error": 1, "reason": str(e)}

    async def reserve_email(self, email: str, label: str = "") -> Dict[str, Any]:
        """Step 2: Reserve (activate) the generated HME address."""
        session = await self._ensure_session()
        payload = {
            "hme": email,
            "label": label or self.label,
            "note": f"Generated by Bybit Manager",
        }
        try:
            async with session.post(
                f"{HME_BASE_V1}/reserve",
                params=DEFAULT_PARAMS,
                json=payload,
            ) as resp:
                return await resp.json()
        except asyncio.TimeoutError:
            return {"error": 1, "reason": "Request timed out"}
        except Exception as e:
            return {"error": 1, "reason": str(e)}

    async def list_emails(self) -> Dict[str, Any]:
        """List all Hide My Email addresses."""
        session = await self._ensure_session()
        try:
            async with session.get(
                f"{HME_BASE_V2}/list",
                params=DEFAULT_PARAMS,
            ) as resp:
                return await resp.json()
        except asyncio.TimeoutError:
            return {"error": 1, "reason": "Request timed out"}
        except Exception as e:
            return {"error": 1, "reason": str(e)}

    async def generate_one(self, label: str = "") -> Optional[str]:
        """Generate and reserve one HME email. Returns the email or None."""
        # Step 1: Generate
        gen_res = await self.generate_email()
        if not gen_res.get("success"):
            err = gen_res.get("error", {})
            reason = (
                gen_res.get("reason", "")
                or (err.get("errorMessage", "") if isinstance(err, dict) else "")
                or str(err)
            )
            logger.error("HME generate failed: %s", reason)
            return None

        email = gen_res["result"]["hme"]
        logger.info("Generated HME: %s", email)

        # Step 2: Reserve
        reserve_res = await self.reserve_email(email, label or self.label)
        if not reserve_res.get("success"):
            err = reserve_res.get("error", {})
            reason = (
                reserve_res.get("reason", "")
                or (err.get("errorMessage", "") if isinstance(err, dict) else "")
                or str(err)
            )
            logger.error("HME reserve failed for %s: %s", email, reason)
            return None

        logger.info("Reserved HME: %s", email)
        return email

    async def generate_batch(
        self,
        count: int,
        label_prefix: str = "bybit",
        concurrency: int = 5,
    ) -> List[str]:
        """Generate multiple HME emails with rate limiting.

        Apple limits ~5 emails per 45 minutes per iCloud account.
        """
        emails = []
        generated = 0

        while generated < count:
            batch_size = min(concurrency, count - generated)
            tasks = [
                self.generate_one(label=f"{label_prefix}-{generated + i + 1}")
                for i in range(batch_size)
            ]
            results = await asyncio.gather(*tasks)
            batch_emails = [e for e in results if e is not None]
            emails.extend(batch_emails)
            generated += batch_size

            if generated < count and batch_emails:
                logger.info(
                    "Batch done (%d/%d). Waiting %ds for rate limit...",
                    generated, count, BATCH_COOLDOWN,
                )
                await asyncio.sleep(BATCH_COOLDOWN)

        return emails


# ================================================================
# FastAPI router integration
# ================================================================

def create_hme_router():
    """Create a FastAPI router for HME management."""
    from fastapi import APIRouter, HTTPException, Query
    from pydantic import BaseModel

    router = APIRouter()

    class GenerateRequest(BaseModel):
        count: int = 1
        label_prefix: str = "bybit"
        cookie_file: str = "config/icloud_cookies.txt"

    class GenerateResponse(BaseModel):
        emails: List[str]
        count: int

    @router.post("/generate", response_model=GenerateResponse)
    async def generate_hme(body: GenerateRequest):
        """Generate Hide My Email aliases."""
        async with HideMyEmailClient(cookie_file=body.cookie_file) as hme:
            emails = await hme.generate_batch(
                count=body.count,
                label_prefix=body.label_prefix,
                concurrency=min(body.count, BATCH_SIZE),
            )
            return GenerateResponse(emails=emails, count=len(emails))

    @router.get("/list")
    async def list_hme(cookie_file: str = Query("config/icloud_cookies.txt")):
        """List all Hide My Email aliases."""
        async with HideMyEmailClient(cookie_file=cookie_file) as hme:
            result = await hme.list_emails()
            if not result.get("success"):
                raise HTTPException(status_code=502, detail="Failed to list HME")
            return result["result"]

    return router
