"""
Frida MCP Server — JSON-RPC 2.0 server for frida_bridge.py.

Protocol: POST /rpc
  Request:  {"jsonrpc": "2.0", "id": N, "method": "...", "params": {...}}
  Response: {"jsonrpc": "2.0", "id": N, "result": ...}
         or {"jsonrpc": "2.0", "id": N, "error": {"code": -1, "message": "..."}}

Listens on 0.0.0.0:8766 (matches FridaMCPClient default port).

Supported methods:
  ping                           — health check
  tools/list                     — list available tools
  tools/call {name, arguments}   — invoke a Frida tool

Tools:
  generate_hook   — generate Frida Interceptor.attach JS (no Frida needed)
  attach_and_run  — inject script into PID via frida CLI
  spawn_and_run   — spawn binary and inject script via frida CLI
  stalker_trace   — run Stalker-based trace via frida CLI
  memory_scan     — run Memory.scan via frida CLI
"""
from __future__ import annotations

import json
import shutil
import subprocess
import sys
import traceback
from http.server import BaseHTTPRequestHandler, HTTPServer
from typing import Any

# ---------------------------------------------------------------------------
# Frida CLI availability check
# ---------------------------------------------------------------------------

FRIDA_AVAILABLE: bool = bool(shutil.which("frida"))

# ---------------------------------------------------------------------------
# Tool implementations
# ---------------------------------------------------------------------------

def _generate_hook(arguments: dict) -> dict:
    """Generate a Frida Interceptor.attach script — purely local, no Frida needed."""
    address   = arguments.get("address", "0x0")
    arg_count = int(arguments.get("arg_count", 4))
    hook_name = arguments.get("hook_name", "auto")
    log_args  = arguments.get("log_args", True)
    log_ret   = arguments.get("log_retval", True)

    if log_args and arg_count > 0:
        args_js = "\n".join(
            f"        console.log('  arg[{i}] =', args[{i}],"
            f" args[{i}].readUtf8String ? tryRead(args[{i}]) : '');"
            for i in range(arg_count)
        )
    else:
        args_js = "        // arg logging disabled"

    ret_js = (
        "        console.log('[<] retval =', retval);"
        if log_ret else
        "        // retval logging disabled"
    )

    script = f"""\
// Frida hook: {hook_name} @ {address}
// Auto-generated by frida-mcp-server

function tryRead(p) {{
    try {{ return p.readUtf8String(); }} catch(_) {{
        try {{ return p.readUtf16String(); }} catch(__) {{ return ''; }}
    }}
}}

const _target = ptr('{address}');
Interceptor.attach(_target, {{
    onEnter: function(args) {{
        console.log('[>] {hook_name} called');
{args_js}
    }},
    onLeave: function(retval) {{
{ret_js}
    }}
}});
console.log('[*] Hook installed: {hook_name} @ {address}');
"""
    return {"script": script, "hook_id": f"hook_{address}"}


def _run_frida(cmd: list[str], timeout: int = 30) -> dict:
    """Execute a frida CLI command and return structured output."""
    if not FRIDA_AVAILABLE:
        return {
            "captures": [],
            "hook_id": "mock",
            "error": (
                "frida CLI not available on this system. "
                "Install with: pip install frida-tools"
            ),
            "mock": True,
        }
    try:
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        lines = [ln.strip() for ln in proc.stdout.splitlines() if ln.strip()]
        captures = [{"type": "output", "message": ln} for ln in lines]
        error = proc.stderr[:500].strip() if proc.returncode != 0 else None
        return {
            "captures": captures,
            "hook_id": "frida_run",
            "error": error,
        }
    except subprocess.TimeoutExpired:
        return {
            "captures": [],
            "hook_id": "frida_run",
            "error": f"frida process timed out after {timeout}s",
        }
    except Exception as exc:
        return {
            "captures": [],
            "hook_id": "frida_run",
            "error": str(exc),
        }


def _attach_and_run(arguments: dict) -> dict:
    """Attach to a running PID and execute a Frida script."""
    pid    = int(arguments.get("pid", 0))
    script = arguments.get("script", "console.log('hello from frida');")
    return _run_frida(["frida", "-p", str(pid), "--no-pause", "-e", script])


def _spawn_and_run(arguments: dict) -> dict:
    """Spawn a binary and execute a Frida script from process entry."""
    binary = arguments.get("binary_path", "")
    args   = arguments.get("args", [])
    script = arguments.get("script", "console.log('hello from frida');")
    cmd    = ["frida", "-f", binary, "--no-pause", "-e", script]
    if args:
        cmd += ["--"] + [str(a) for a in args]
    return _run_frida(cmd)


def _stalker_trace(arguments: dict) -> list:
    """Run a Stalker-based call summary trace on a PID."""
    pid      = int(arguments.get("pid", 0))
    max_inst = int(arguments.get("max_instructions", 10000))

    stalker_js = f"""\
Stalker.follow(Process.getCurrentThreadId(), {{
    events: {{ call: true, ret: false, exec: false }},
    onCallSummary: function(summary) {{
        for (const [addr, count] of Object.entries(summary)) {{
            const sym = DebugSymbol.fromAddress(ptr(addr));
            send({{type: 'call', address: addr, count: count, sym: sym.toString()}});
        }}
    }}
}});
// Unfollow after 2 seconds
setTimeout(function() {{
    Stalker.unfollow(Process.getCurrentThreadId());
    console.log('[*] Stalker unfollow complete, max_instructions={max_inst}');
}}, 2000);
"""
    result = _run_frida(["frida", "-p", str(pid), "--no-pause", "-e", stalker_js])
    return result.get("captures", [])


def _memory_scan(arguments: dict) -> list:
    """Scan process memory for a byte pattern (Frida wildcard syntax)."""
    pid         = int(arguments.get("pid", 0))
    pattern     = arguments.get("pattern", "")
    range_start = arguments.get("range_start", "0x1000")
    range_size  = int(arguments.get("range_size", 0x7FFFFFFF))

    scan_js = f"""\
Memory.scan(ptr('{range_start}'), {range_size}, '{pattern}', {{
    onMatch: function(address, size) {{
        send({{type: 'match', address: address.toString(), size: size}});
    }},
    onError: function(reason) {{
        console.log('[!] scan error:', reason);
    }},
    onComplete: function() {{
        console.log('[*] Memory scan complete');
    }}
}});
"""
    result = _run_frida(["frida", "-p", str(pid), "--no-pause", "-e", scan_js])
    return result.get("captures", [])


# ---------------------------------------------------------------------------
# Tool registry
# ---------------------------------------------------------------------------

TOOLS: dict[str, Any] = {
    "generate_hook":  _generate_hook,
    "attach_and_run": _attach_and_run,
    "spawn_and_run":  _spawn_and_run,
    "stalker_trace":  _stalker_trace,
    "memory_scan":    _memory_scan,
}

TOOL_DESCRIPTIONS: list[dict] = [
    {
        "name": "generate_hook",
        "description": "Generate a Frida Interceptor.attach JS script for a given address.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "address":    {"type": "string", "description": "Target function address (hex)"},
                "arg_count":  {"type": "integer", "description": "Number of arguments to log"},
                "hook_name":  {"type": "string",  "description": "Human-readable hook label"},
                "log_args":   {"type": "boolean", "description": "Log arguments on enter"},
                "log_retval": {"type": "boolean", "description": "Log return value on leave"},
            },
            "required": ["address"],
        },
    },
    {
        "name": "attach_and_run",
        "description": "Attach to a running process by PID and inject a Frida script.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "pid":    {"type": "integer", "description": "Target process PID"},
                "script": {"type": "string",  "description": "Frida JavaScript to inject"},
            },
            "required": ["pid", "script"],
        },
    },
    {
        "name": "spawn_and_run",
        "description": "Spawn a binary under Frida and inject a script from the start.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "binary_path": {"type": "string", "description": "Path to the executable"},
                "args":        {"type": "array",  "description": "Arguments for the binary"},
                "script":      {"type": "string", "description": "Frida JavaScript to inject"},
            },
            "required": ["binary_path", "script"],
        },
    },
    {
        "name": "stalker_trace",
        "description": "Trace code execution with Frida Stalker (call summary).",
        "inputSchema": {
            "type": "object",
            "properties": {
                "pid":              {"type": "integer", "description": "Target process PID"},
                "start_address":    {"type": "string",  "description": "Optional start address"},
                "follow_calls":     {"type": "boolean", "description": "Follow calls"},
                "max_instructions": {"type": "integer", "description": "Instruction limit"},
            },
            "required": ["pid"],
        },
    },
    {
        "name": "memory_scan",
        "description": "Scan process memory for a byte pattern using Frida Memory.scan.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "pid":         {"type": "integer", "description": "Target process PID"},
                "pattern":     {"type": "string",  "description": "Byte pattern (Frida wildcard syntax)"},
                "range_start": {"type": "string",  "description": "Start address for scan"},
                "range_size":  {"type": "integer", "description": "Number of bytes to scan"},
            },
            "required": ["pid", "pattern"],
        },
    },
]


# ---------------------------------------------------------------------------
# JSON-RPC 2.0 dispatch
# ---------------------------------------------------------------------------

def _jsonrpc_error(req_id: Any, code: int, message: str) -> dict:
    return {
        "jsonrpc": "2.0",
        "id": req_id,
        "error": {"code": code, "message": message},
    }


def _jsonrpc_result(req_id: Any, result: Any) -> dict:
    return {
        "jsonrpc": "2.0",
        "id": req_id,
        "result": result,
    }


def dispatch(request: dict) -> dict:
    """Dispatch a JSON-RPC 2.0 request and return a response dict."""
    req_id = request.get("id")
    method = request.get("method", "")
    params = request.get("params") or {}

    # --- ping ---
    if method == "ping":
        return _jsonrpc_result(req_id, {"pong": True, "frida_available": FRIDA_AVAILABLE})

    # --- tools/list ---
    if method == "tools/list":
        return _jsonrpc_result(req_id, TOOL_DESCRIPTIONS)

    # --- tools/call ---
    if method == "tools/call":
        tool_name = params.get("name", "")
        arguments = params.get("arguments") or {}

        fn = TOOLS.get(tool_name)
        if fn is None:
            return _jsonrpc_error(req_id, -32601, f"Unknown tool: {tool_name!r}")

        try:
            result = fn(arguments)
            return _jsonrpc_result(req_id, result)
        except Exception as exc:
            traceback.print_exc()
            return _jsonrpc_error(req_id, -32000, str(exc))

    # --- unknown method ---
    return _jsonrpc_error(req_id, -32601, f"Method not found: {method!r}")


# ---------------------------------------------------------------------------
# HTTP handler
# ---------------------------------------------------------------------------

class MCPHandler(BaseHTTPRequestHandler):
    """HTTP handler that wraps JSON-RPC 2.0 dispatch on POST /rpc."""

    def log_message(self, fmt: str, *args: Any) -> None:  # type: ignore[override]
        print(f"[frida-mcp] {self.address_string()} — {fmt % args}", flush=True)

    def _send_json(self, status: int, body: dict) -> None:
        data = json.dumps(body, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def do_GET(self) -> None:
        if self.path in ("/health", "/"):
            self._send_json(200, {
                "status": "ok",
                "server": "frida-mcp-server",
                "frida_available": FRIDA_AVAILABLE,
                "tools": [t["name"] for t in TOOL_DESCRIPTIONS],
            })
        else:
            self.send_response(404)
            self.end_headers()

    def do_POST(self) -> None:
        if self.path == "/rpc":
            length = int(self.headers.get("Content-Length", 0))
            raw    = self.rfile.read(length)

            try:
                request = json.loads(raw)
            except json.JSONDecodeError as exc:
                self._send_json(400, _jsonrpc_error(None, -32700, f"Parse error: {exc}"))
                return

            print(
                f"[frida-mcp] RPC method={request.get('method')!r} "
                f"id={request.get('id')}",
                flush=True,
            )

            response = dispatch(request)
            self._send_json(200, response)

        elif self.path == "/health":
            self._send_json(200, {
                "status": "ok",
                "frida_available": FRIDA_AVAILABLE,
            })

        else:
            self.send_response(404)
            self.end_headers()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def run(host: str = "0.0.0.0", port: int = 8766) -> None:
    print(f"[frida-mcp] Starting Frida MCP server on {host}:{port}", flush=True)
    print(f"[frida-mcp] frida CLI available: {FRIDA_AVAILABLE}", flush=True)
    if not FRIDA_AVAILABLE:
        print(
            "[frida-mcp] WARNING: frida not found in PATH. "
            "generate_hook works locally; attach/spawn/stalker/scan return mocks.",
            flush=True,
        )
    print(f"[frida-mcp] Tools: {', '.join(TOOLS)}", flush=True)
    server = HTTPServer((host, port), MCPHandler)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("[frida-mcp] Stopped.", flush=True)


if __name__ == "__main__":
    _port = int(sys.argv[1]) if len(sys.argv) > 1 else 8766
    run(port=_port)
