"""
Awarding enums — mirrors the DB enum values.
"""

from __future__ import annotations

from ._base import BybitEnum


class AwardingStatus(BybitEnum):
    UNKNOWN = "AWARDING_STATUS_UNKNOWN"
    UNCLAIMED = "AWARDING_STATUS_UNCLAIMED"
    UNCLAIMED_EXPIRED = "AWARDING_STATUS_UNCLAIMED_EXPIRED"
    PENDING = "AWARDING_STATUS_PENDING"
    CLAIMED = "AWARDING_STATUS_CLAIMED"


class AwardingUsingStatus(BybitEnum):
    UNKNOWN = "AWARDING_USING_STATUS_UNKNOWN"
    IN_USE = "AWARDING_USING_STATUS_IN_USE"
    FINISHED = "AWARDING_USING_STATUS_FINISHED"
    EXPIRED = "AWARDING_USING_STATUS_EXPIRED"
    PENDING = "AWARDING_USING_STATUS_PENDING"
    FAILURE = "AWARDING_USING_STATUS_FAILURE"
    TRANSFER = "AWARDING_USING_STATUS_TRANSFER"


class AwardType(BybitEnum):
    UNKNOWN = "AWARD_TYPE_UNKNOWN"
    CASH_CARD = "AWARD_TYPE_CASH_CARD"
    SERVICE_CASH_CARD = "AWARD_TYPE_SERVICE_CASH_CARD"
    TRADING_FEE_DISCOUNT = "AWARD_TYPE_TRADING_FEE_DISCOUNT_CARD"
    TASK = "AWARD_TYPE_TASK"
    BYFI_INTEREST = "AWARD_TYPE_BYFI_INTEREST"
    SPOT_AIR_DROP = "AWARD_TYPE_SPOT_AIR_DROP"
    VIP_EXPERIENCE = "AWARD_TYPE_VIP_EXPERIENCE_CARD"
    VOTES_CARD = "AWARD_TYPE_VOTES_CARD"
    TRADING_VOUCHER = "AWARD_TYPE_TRADING_VOUCHER"
    REWARD = "AWARD_TYPE_REWARD"
    LOSS_COVER = "AWARD_TYPE_LOSS_COVER_VOUCHER"
    APR_BOOSTER = "AWARD_TYPE_APR_BOOSTER"
    POINTS = "AWARD_TYPE_POINTS"
    CREDIT = "AWARD_TYPE_CREDIT"
