"""
RECOVERED: ccxt.static_dependencies
"""
# from .ecdsa import ...
# from .ethereum import ...
# from .keccak import ...
# from .marshmallow import ...
# from .msgpack import ...
# from .parsimonious import ...
# from .starknet import ...
# from .starkware import ...
# from .sympy import ...
# from .toolz import ...
