"""
RECOVERED: ccxt.static_dependencies.marshmallow
"""
# from .base import ...
# from .class_registry import ...
# from .decorators import ...
# from .error_store import ...
# from .exceptions import ...
# from .fields import ...
# from .orderedset import ...
# from .schema import ...
# from .types import ...
# from .utils import ...
# from .validate import ...
# from .warnings import ...
